### ISSUE TITLE
Why can't we use this project at the production level yet?

### ISSUE THREAD

**Issue by paperfrog1228** [paritytech/desub#83]
`† This software is experimental, and not intended for production use yet. Use at your own risk.`

What's the problem? If I do, when can I use it at the production level?

If V15 comes out one day, I'm curious if you'll apply for it :)

**Comment by dvdplm** [comment]
No known problems, the library works. Simply that this library has not been deployed in production for very long and we take stability very seriously. It is fully maintained, so any issues that might pop up, we're here to help. :)
