### ISSUE TITLE
support frame-metadata 15.0.0

### ISSUE THREAD

**Issue by gilescope** [paritytech/desub#97]
v15 is here.

**Comment by gilescope** [comment]
got the main code compiling. working on the tests.

**Comment by jsdw** [comment]
My approach for this would be to have `desub-current` be a wrapper around https://github.com/paritytech/scale-value/, which uses frame-metadata 15 already, and IMO does a better job of decoding SCALE bytes anyway (especially everything bitvec related) :)

**Comment by gilescope** [comment]
Yeah that would be ideal. I wasn't sure just how big a change that was. Also I was wondering if maybe the answer was a new crate that did what desub does but using scale-value. The reason I might be leaning towards that is desub-common has a lot of dependencies. I'm not convinced we need all of them and maybe a lot of them are due to the legacy? Thoughts?

**Comment by jsdw** [comment]
Closed by #115
